USE master;
GO

IF EXISTS (SELECT 1 FROM sys.databases WHERE [name] = N'$(HIREME_WEBAPI_DB_NAME)')
BEGIN
    ALTER DATABASE $(HIREME_WEBAPI_DB_NAME) SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

    DROP DATABASE $(HIREME_WEBAPI_DB_NAME);
END;
GO

CREATE DATABASE $(HIREME_WEBAPI_DB_NAME);
GO

USE $(HIREME_WEBAPI_DB_NAME);
GO
